[settings]

    [settings.sms]
        # SMS API settings

    [settings.email]
        # Email API settings
        to = "" # Destination email address
        login = "" # SMTP server login email address
        from = "" # Sender email address
        secret = "" # App key
        port = "" # SMTP SSL port
        server = "" # SMTP server FQDN
        body = "" # Body of your message

    [settings.tele]
        # Telegram API settings

[tells]

    # Add your tells here
    # e.g. car_wash = ["Get the car washed!", "st", "0 0 1 * *"]