[settings]

    [settings.sms]
        # SMS API settings


    [settings.email]
        # Email API settings

    [settings.tele]
        # Telegram API settings
        chat_id = ""
        bot_token = ""

[tells]

    # Add your tells here
    # e.g. car_wash = ["Get the car washed!", "st", "0 0 1 * *"]